import './assets/fonts/Roboto-Thin.ttf'
import './assets/fonts/Roboto-Light.ttf'
import './assets/fonts/Roboto-Regular.ttf'
import './assets/fonts/Roboto-Medium.ttf'
import './assets/fonts/Roboto-Bold.ttf'
